import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AppHeader from "@/app/components/AppHeader";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={"font-open-sans min-h-screen bg-stone-100"}
      >
          <div className={"container mx-auto flex min-h-screen flex-col gap-y-4"}>
            <AppHeader />

            <main className={"flex-grow flex-col bg-white px-8 py-4"}>
              {children}
            </main>
            {/*<ReactQueryDevtools />*/}
          </div>
      </body>
    </html>
  );
}
